### ISSUE TITLE
"Самый последний вопрос 

### ISSUE THREAD

**Issue by stas-yushkov** [AlexKTest/fe33-module-8#1]
"Самый последний вопрос - в конце занятия, чтоб побольше успеть сейчас

Фриланс. Сейчас доверстываю один проект. с него ущло 3 или 4 разраба. чем дальше тем больше мещанина в коде. 
Я правильно понимаю, что в нормальных компаниях, или в коммандном проекте на обучении  - важнее всего договориться о стандартах прежде чем пилить проект? именование, методология, компоненты, както в общем нарисовать карту сайта или приложения, майндмап, возможно..." @AlexKTest

**Comment by AlexKTest** [comment]
Именование и похожие вещи обычно решаются правильной настройкой приттиера. Конечно, структуру и техрологии нужно продумать. Ну а потом я бы  назаводил тасок в стиле "привести такие-то файлы/папки к общему виду", "везде перейти на такую-то технологию" итд когда понятно что исправлять. Ну и рефакторить по очереди.

**Comment by stas-yushkov** [comment]
Спасибо)
